In [45]:
%run base_functions.ipynb

In [3]:
today_date = datetime.today();
urls=[
    MyURL('NSE_INDEXES','https://www1.nseindia.com/homepage/Indices1.json')
    ,MyURL('NSE_GAINER','https://www1.nseindia.com/live_market/dynaContent/live_analysis/gainers/niftyGainers1.json')
    ,MyURL('SERIES_CHANGE','https://archives.nseindia.com/content/equities/series_change.csv','csv')
   
     ]
for myurl in urls:
    try:
        data = loadURL(myurl,True)
        display(data)
    except Exception:
        print('Error loading URL ', myurl.url)

loading url  NSE_INDEXES https://www1.nseindia.com/homepage/Indices1.json
loading cookies for https://www.nseindia.com/

{'https://www.nseindia.com/': <Response [200]>}

NSE_INDEXES https://www1.nseindia.com/homepage/Indices1.json <Response [200]>

                 name  lastPrice  change pChange                 imgFileName
0   NIFTY 50 Pre Open  13,996.10   14.35    0.10  NIFTY_50_Pre_Open_open.png
1            NIFTY 50  14,018.50   36.75    0.26           NIFTY_50_open.png
2       NIFTY NEXT 50  32,765.95  257.40    0.79      NIFTY_NEXT_50_open.png
3     NIFTY100 LIQ 15   3,360.60   11.50    0.34    NIFTY100_LIQ_15_open.png
4          NIFTY BANK  31,225.85  -38.20   -0.12         NIFTY_BANK_open.png
5           INDIA VIX    19.5600   -1.54   -7.28          INDIA_VIX_open.png
6           NIFTY 100  14,137.55   46.80    0.33          NIFTY_100_open.png
7           NIFTY 500  11,574.85   56.55    0.49          NIFTY_500_open.png
8    NIFTY MIDCAP 100  21,090.95  248.45    1.19   NIFTY_MIDCAP_100_open.png
9     NIFTY MIDCAP 50   5,965.70   93.10    1.59    NIFTY_MIDCAP_50_open.png
10        NIFTY INFRA   3,674.20   23.25    0.64        NIFTY_INFRA_open.png
11       NIFTY REALTY     316.40    2.55    0.81       NIFTY_REALTY_open.png
12       NIFTY ENERGY  16,976.20   53.70    0.32       NIFTY_ENERGY_open.png
13         NIFTY FMCG  34,391.85  214.75    0.63         NIFTY_FMCG_open.png
14          NIFTY MNC  15,757.65  104.20    0.67          NIFTY_MNC_open.png
15       NIFTY PHARMA  13,001.95   86.05    0.67       NIFTY_PHARMA_open.png
16          NIFTY PSE   2,815.40   18.30    0.65          NIFTY_PSE_open.png
17     NIFTY PSU BANK   1,809.60   56.90    3.25     NIFTY_PSU_BANK_open.png
18  NIFTY SERV SECTOR  19,660.50   34.60    0.18  NIFTY_SERV_SECTOR_open.png
19           NIFTY IT  24,456.10  204.75    0.84           NIFTY_IT_open.png
20   NIFTY SMLCAP 100   7,169.75   82.15    1.16   NIFTY_SMLCAP_100_open.png
21          NIFTY 200   7,263.00   31.20    0.43          NIFTY_200_open.png
22         NIFTY AUTO   9,272.50   79.00    0.86         NIFTY_AUTO_open.png
23        NIFTY MEDIA   1,658.95   10.00    0.61        NIFTY_MEDIA_open.png
24        NIFTY METAL   3,258.85    4.20    0.13        NIFTY_METAL_open.png
25  NIFTY DIV OPPS 50   2,881.80   24.45    0.86  NIFTY_DIV_OPPS_50_open.png
26  NIFTY COMMODITIES   3,815.90   15.30    0.40  NIFTY_COMMODITIES_open.png
27  NIFTY CONSUMPTION   5,947.70   35.00    0.59  NIFTY_CONSUMPTION_open.png
28         NIFTY CPSE   1,639.05   10.40    0.64         NIFTY_CPSE_open.png
29  NIFTY FIN SERVICE  15,184.50  -23.50   -0.15  NIFTY_FIN_SERVICE_open.png
30  NIFTY GROWSECT 15   7,059.05   -4.20   -0.06  NIFTY_GROWSECT_15_open.png
31   NIFTY50 VALUE 20   6,893.45   52.50    0.77   NIFTY50_VALUE_20_open.png
32  NIFTY50 TR 2X LEV   8,104.05   41.80    0.52  NIFTY50_TR_2X_LEV_open.png
33  NIFTY50 PR 2X LEV   6,099.95   31.45    0.52  NIFTY50_PR_2X_LEV_open.png
34  NIFTY50 TR 1X INV     272.20   -0.70   -0.26  NIFTY50_TR_1X_INV_open.png
35  NIFTY50 PR 1X INV     313.60   -0.80   -0.25  NIFTY50_PR_1X_INV_open.png
36     NIFTY ALPHA 50  20,096.30  259.50    1.31     NIFTY_ALPHA_50_open.png
37    NIFTY50 EQL WGT  14,675.60   58.95    0.40    NIFTY50_EQL_WGT_open.png
38   NIFTY100 EQL WGT  15,631.10  100.55    0.65   NIFTY100_EQL_WGT_open.png
39  NIFTY100 LOWVOL30  10,928.60   48.05    0.44  NIFTY100_LOWVOL30_open.png
40   NIFTY MID LIQ 15   5,210.75   75.85    1.48   NIFTY_MID_LIQ_15_open.png
41     NIFTY PVT BANK  17,196.50  -55.25   -0.32     NIFTY_PVT_BANK_open.png
42  NIFTY100 QUALTY30   3,315.70   14.45    0.44  NIFTY100_QUALTY30_open.png
43    NIFTY GS 8 13YR   2,256.88    0.30    0.01    NIFTY_GS_8_13YR_open.png
44      NIFTY GS 10YR   2,029.67   -0.96   -0.05      NIFTY_GS_10YR_open.png
45  NIFTY GS 10YR CLN     966.24   -0.61   -0.06  NIFTY_GS_10YR_CLN_open.png
46     NIFTY GS 4 8YR   2,408.57    0.07    0.00     NIFTY_GS_4_8YR_open.png
47   NIFTY GS 11 15YR   2,442.42    3.24    0.13   NIFTY_GS_11_15YR_open.png
48  NIFTY GS 15YRPLUS   2,687.03    0.48    0.02  NIFTY_GS_15YRPLUS_open.png
49  NIFTY GS COMPSITE   2,303.06    0.78    0.03  NIFTY_GS_COMPSITE_open.png
50   NIFTY MIDCAP 150   7,953.30   90.40    1.15   NIFTY_MIDCAP_150_open.png
51    NIFTY SMLCAP 50   3,579.95   44.90    1.27    NIFTY_SMLCAP_50_open.png
52   NIFTY SMLCAP 250   6,146.15   69.95    1.15   NIFTY_SMLCAP_250_open.png
53   NIFTY MIDSML 400   7,307.50   83.10    1.15   NIFTY_MIDSML_400_open.png
54  NIFTY200 QUALTY30  12,317.70   64.10    0.52  NIFTY200_QUALTY30_open.png

loading url  NSE_GAINER https://www1.nseindia.com/live_market/dynaContent/live_analysis/gainers/niftyGainers1.json
NSE_GAINER https://www1.nseindia.com/live_market/dynaContent/live_analysis/gainers/niftyGainers1.json <Response [200]>

,symbol,series,openPrice,highPrice,lowPrice,ltp,previousPrice,netPrice,tradedQuantity,turnoverInLakhs,lastCorpAnnouncementDate,lastCorpAnnouncement
0,ADANIPORTS,EQ,485.00,508.00,482.55,505.00,483.75,4.39,"78,15,730","38,731.63",17-Jun-2020,Annual General Meeting
1,TCS,EQ,"2,880.00","2,940.00","2,879.00","2,932.00","2,862.75",2.42,"26,81,440","78,124.29",14-Jan-2021,Interim Dividend
2,ITC,EQ,209.90,214.20,209.30,213.90,209.00,2.34,"1,95,27,333","41,417.47",06-Jul-2020,Dividend - Rs 10.15 Per Share
3,M&M,EQ,725.00,744.75,723.00,731.80,720.60,1.55,"95,43,128","70,388.20",16-Jul-2020,Annual General Meeting/Dividend - Rs 2.35 Per ...
4,SBIN,EQ,274.90,280.00,274.40,279.05,274.95,1.49,"2,45,31,791","68,279.33",15-Jun-2018,Annual General Meeting/ Change In Registrar An...
5,TATAMOTORS,EQ,184.95,187.00,184.50,186.55,183.85,1.47,"2,73,34,421","50,751.82",18-Jul-2016,Dividend - Re 0.20/- Per Share
6,BHARTIARTL,EQ,512.25,516.40,508.20,515.00,509.70,1.04,"1,01,85,843","52,143.37",06-Aug-2020,Dividend - Rs 2 Per Share
7,BAJAJ-AUTO,EQ,"3,446.00","3,494.00","3,446.00","3,479.00","3,444.05",1.01,"4,21,643","14,622.92",03-Mar-2020,Interim Dividend - Rs 120 Per Share
8,CIPLA,EQ,822.80,828.95,820.65,827.30,819.95,0.90,"24,74,916","20,446.77",11-Aug-2020,Annual General Meeting
9,SUNPHARMA,EQ,592.50,599.75,585.85,597.70,592.35,0.90,"82,29,768","48,807.46",19-Aug-2020,Annual General Meeting/Dividend - Re 1 Per Share

loading url  SERIES_CHANGE https://archives.nseindia.com/content/equities/series_change.csv
SERIES_CHANGE https://archives.nseindia.com/content/equities/series_change.csv <Response [200]>

,Symbol,Security,From Series,To Series,Change Date,Remarks
0,AARVEEDEN,Aarvee Denims & Exports Limited,EQ,BE,31-Dec-2020,-
1,ALPSINDUS,Alps Industries Limited,EQ,BE,31-Dec-2020,-
2,BASML,Bannari Amman Spinning Mills Limited,EQ,BE,31-Dec-2020,-
3,BHAGYANGR,Bhagyanagar India Limited,EQ,BE,31-Dec-2020,-
4,GENUSPAPER,Genus Paper & Boards Limited,EQ,BE,31-Dec-2020,-
5,GISOLUTION,GI Engineering Solutions Limited,EQ,BE,31-Dec-2020,-
6,KHANDSE,Khandwala Securities Limited,EQ,BE,31-Dec-2020,-
7,MCL,Madhav Copper Limited,EQ,BE,31-Dec-2020,-
8,MIRCELECTR,MIRC Electronics Limited,EQ,BE,31-Dec-2020,-
9,MRO-TEK,MRO-TEK Realty Limited,EQ,BE,31-Dec-2020,-
10,NAHARSPING,Nahar Spinning Mills Limited,EQ,BE,31-Dec-2020,-
11,NKIND,NK Industries Limited,EQ,BE,31-Dec-2020,-
12,RAMKY,Ramky Infrastructure Limited,EQ,BE,31-Dec-2020,-
13,SHYAMTEL,Shyam Telecom Limited,EQ,BE,31-Dec-2020,-
14,SURYALAXMI,Suryalakshmi Cotton Mills Limited,EQ,BE,31-Dec-2020,-

In [4]:

file_types=["INDEX","CM","WDM","FO","SME","SLBS","COM","CD","NBF","CBM"]
file_days=['PreviousDay','FutureDay','CurrentDay']
report_urls = []
base_url = 'https://www.nseindia.com/api/daily-reports?key='
for file_type in file_types:
    data = requests.get(base_url+file_type,headers=chrome_headers,cookies=get_cookies()).json()
    for file_day in file_days:
        for file in data[file_day]:
            report_urls.append(MyURL(file['displayName'],file['filePath']+file['fileActlName'],'csv'))

In [5]:
print('total url found',len(report_urls))

total url found 269

In [ ]:
report_urls.sort(key=lambda x: x.url)
for myurl in filter(lambda item: '.csv' in item.url , report_urls):
    try:
        loadURL(myurl,True)
    except Exception:
        print('Error loading URL ', myurl)

In [ ]:
empty_data_url = [a for a in report_urls if a.data is None]
url_with_data = [a for a in report_urls if a.data is not None]

In [ ]:
myurl = MyURL('Historical Data','https://www1.nseindia.com/products/dynaContent/common/productsSymbolMapping.jsp?symbol=PNB&segmentLink=3&symbolCount=2&series=ALL&dateRange=+&fromDate=01-11-2020&toDate=31-12-2020&dataType=PRICEVOLUMEDELIVERABLE'
              ,'html',domain=nse1_base_url)
loadURL(myurl,True)
myurl.data[0]['Symbol'].unique()

In [ ]:
parent_url = 'https://www1.nseindia.com/'
symb_request = 'https://www1.nseindia.com/marketinfo/sym_map/symbolCount.jsp?symbol=PNB'

parent_page = requests.get(parent_url,headers=chrome_headers)
parent_page = requests.get(symb_request,headers=chrome_headers,cookies=parent_page.cookies)
parent_page.text

In [ ]:
hist_price_url = 'https://www1.nseindia.com/products/dynaContent/common/productsSymbolMapping.jsp?symbol=PNB&segmentLink=3&symbolCount=2&series=ALL&dateRange=12month&fromDate=&toDate=&dataType=PRICEVOLUMEDELIVERABLE'

hist_response =  requests.get(hist_price_url,headers=chrome_headers,cookies=get_cookies(parent_url))
hist_response

In [ ]:
df_hist = pd.read_html(hist_response.text)

In [ ]:
df_hist[0]

In [ ]:
for url in url_with_data:
    print(str(url))
    display(url.data)

In [47]:
file_name= 'my_portfolio.txt'
sell_tax_overhead=0

port_data = load_portfolio_file(file_name)
port_data

,SYMBOL,DATE,INVESTMENT,REAL,QTY,SELL_DATE,AVG,DAYS,CATEGORY
0,PNB,2020-12-08,"7,815.00",0.00,200.00,NaT,39.08,232,< 1 Year
1,WIPRO,2020-12-23,"3,795.95",9.25,10.00,NaT,379.59,217,< 1 Year
2,UNITECH,2013-12-05,"9,260.20",0.00,400.00,NaT,23.15,2792,> 5 Year
3,NHPC,2020-12-04,"9,044.00","2,251.00",0.00,2021-07-26,inf,234,< 1 Year
4,NHPC,2013-09-06,"13,566.60","1,530.00",0.00,2021-07-26,inf,2880,> 5 Year
5,RAYMOND,2020-12-21,"5,297.78",0.00,15.00,NaT,353.19,219,< 1 Year
6,SJVN,2020-12-11,"7,643.70",499.50,300.00,NaT,25.48,229,< 1 Year
7,HAL,2021-01-06,"4,785.00",69.38,5.00,NaT,957.00,203,< 1 Year
8,RECLTD,2021-01-12,"7,198.15",250.00,50.00,NaT,143.96,197,< 1 Year
9,LICHSGFIN,2021-01-28,"4,006.00",0.00,10.00,NaT,400.60,181,< 1 Year
10,HDFCLIFE,2021-02-16,"10,469.25",0.00,15.00,NaT,697.95,162,< 1 Year
11,CEREBRAINT,2021-02-16,"7,143.00","3,692.00",0.00,2021-06-05,inf,109,< 1 Year
12,CENTRALBK,2021-02-17,"8,450.00","1,850.00",0.00,2021-06-17,inf,120,< 1 Year
13,IRCON,2021-03-10,"8,806.00",0.00,200.00,NaT,44.03,140,< 1 Year
14,AMARAJABAT,2021-05-25,"11,718.00",0.00,16.00,NaT,732.38,64,< 1 Year
15,ENDURANCE,2021-05-26,"10,268.00",0.00,7.00,NaT,"1,466.86",63,< 1 Year
16,BARBEQUE,2021-05-27,"8,906.00",0.00,10.00,NaT,890.60,62,< 1 Year
17,JKLAKSHMI,2021-06-02,"10,846.00",0.00,20.00,NaT,542.30,56,< 2 Month
18,LICHSGFIN,2021-06-28,"10,320.70",0.00,22.00,NaT,469.12,30,< 2 Month
19,HDFCLIFE,2021-06-28,"10,503.75",0.00,15.00,NaT,700.25,30,< 2 Month
20,DCBBANK,2012-05-14,"6,654.00","9,039.36",0.00,2021-07-02,inf,3336,> 5 Year
21,WIPRO,2021-07-14,"19,670.00",0.00,35.00,NaT,562.00,14,< 2 Month
22,HDFCBANK,2021-07-23,"21,818.25",0.00,15.00,NaT,"1,454.55",5,< 2 Month
23,TANLA,2020-12-08,"20,646.15","1,720.23",0.00,2021-02-26,inf,80,< 1 Year
24,TANLA,2020-12-21,"9,539.19","4,357.79",0.00,2021-07-26,inf,217,< 1 Year

In [42]:

    
port_data[['DATE','SELL_DATE']].apply(count_days,axis=1)

0      232
1      217
2     2792
3      234
4     2880
5      219
6      229
7      203
8      197
9      181
10     162
11      17
12     120
13     140
14      64
15      63
16      62
17      56
18      30
19      30
20    3336
21      14
22       5
23      80
24     217
dtype: int64